core/urls.py
from core import views
from django.urls import path
from core import views
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_month_to_cart,
    add_to_cart,
    admin_user,
    order_list,
    remove_month_from_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    aboutUs,
    admin_item,
    user_list,
    pedidos_user, buscador, edit_user, delete_user
    
)

app_name = 'core'

urlpatterns = [
    path('home/', HomeView.as_view(), name='home'),
    path('all-products/', views.products, name='products'),
    path('category/<str:category>/', HomeView.as_view(), name='home-category'),
    path('manufacturer/<str:fabricante>/', HomeView.as_view(), name='home-fabricante'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-month-to-cart/rental/<slug>/', add_month_to_cart, name='add-month-to-cart'),
    path('add-to-cart/purchase/<slug>/', add_to_cart, name='add-to-cart-purchase'),
    path('add-to-cart/rental/<slug>/', add_to_cart, name='add-to-cart-rental'),
    path('admin-item/<slug>/', admin_item, name='admin-item'),
    path('admin-user/<user>/', admin_user, name='admin-user'),
    path('users/edit/<int:user_id>/', edit_user, name='edit_user'),
    path('users/delete/<int:user_id>/', delete_user, name='delete_user'),
    path('user-list/', user_list, name='user-list'),
    path('order-list/', order_list, name='order-list'),
    path('buscador/', buscador, name='buscador'),
    path('pedidos/', pedidos_user, name='pedidos_user'), 
    path('remove-month-from-cart/rental/<slug>/', remove_month_from_cart, name='remove-month-from-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('opinions/' ,views.opinions,name='opinions'),
    path('opinions/<int:opinion_id>/', views.opinions_details,name="opinionDetails"),
    path('opinions/create/<slug>', views.create_opinion,name="opinionCreate"),
    path('opinions/<int:opinion_id>/addResponse/', views.createResponse,name="responseCreate"),
    path('claims/create', views.create_claim, name='create-claim'),
    path('claims/list', views.claims_list, name='claims-list'),
    path('claims/<int:claim_id>', views.claim_details, name='claim-details'),
    path('claims/<int:claim_id>/change', views.change_claim_status, name='change-claim-status'),
    path('profile/',views.profile),
    path('about-us/' ,aboutUs,name='about-us'),
    path('condiciones/' ,views.condiciones,name='condiciones'),
    path('politica/' ,views.politica,name='politica'),
    path('borrar_producto/<int:product_id>/', views.delete_product, name='delete_product'),
    path('add-item', views.add_item, name='add_item'),
    path('', views.escaparate, name='escaparate')
]

core/models.py
import re
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models.signals import post_migrate
from django.dispatch import receiver
from django.db.models import Sum
from django.forms import ValidationError
from django.shortcuts import reverse
from django_countries.fields import CountryField

from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
        email = models.EmailField(unique=True)
        USERNAME_FIELD = 'email'
        REQUIRED_FIELDS = ['username']

CATEGORY_CHOICES = (
    ('MP', 'Maquinaria Pesada'),
    ('MS', 'Maquinaria Semipesada'),
    ('ML', 'Maquinaria Ligera')
)

FABRICANTE_CHOICES = (
    ('CAT', 'Caterpillar'),
    ('KMT', 'Komatsu'),
    ('X', 'XCMG'),
    ('JD', 'John Deere'),
    ('S', 'Sany'),

)

DISPONIBILITY_CHOICES = (
    ('D', 'Disponible'),
    ('ND', 'No disponible')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

STATE_CHOICES = (
    ('CF', 'Confirmado'),
    ('EV', 'Enviado'),
    ('EP', 'En preparacion'),
    ('RB', 'Recibido'),
    ('AN', 'Anulado'),
    
)

CLAIM_CHOICES = (
    ('PR', 'Por revisar'),
    ('EP', 'En proceso'),
    ('RV', 'Revisada'),
)
def dni_validator(value):
        if not value or not (len(value) == 9 and value[:-1].isdigit() and value[-1].isalpha()):
            raise ValidationError('El DNI debe tener 8 números seguidos de una letra.')

def telefono_validator(value):
    # Se permite el formato (+34) 123-456-789 o 123456789
    pattern = re.compile(r'^(\+\d{1,3}\s?)?(\d{3}[-.\s]?){2}\d{3}$')
    
    if not value or not pattern.match(value):
        raise ValidationError('El número de teléfono no tiene un formato válido.')

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    DNI = models.CharField(max_length=9, blank=True, null=True, validators=[dni_validator])
    telefono = models.CharField(max_length=9, blank=True, null=True, validators=[telefono_validator])
    
    primary_address = models.ForeignKey(
        'Address', related_name='primary_address', on_delete=models.SET_NULL, blank=True, null=True)
    
    card_number = models.BigIntegerField(blank=True, null=True)
    card_expiry = models.PositiveIntegerField(blank=True, null=True)
    card_expiry_month = models.PositiveSmallIntegerField(blank=True, null=True)
    card_expiry_year = models.PositiveIntegerField(blank=True, null=True)
    card_cvc = models.PositiveSmallIntegerField(blank=True, null=True)
    has_card_details = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username
    
    

class Fabricante(models.Model):
    initials = models.CharField(max_length=3)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Category(models.Model):
    initials = models.CharField(max_length=3)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

@receiver(post_migrate)
def create_default_instances(sender, **kwargs):
    if sender.name == 'core':
        for fabricante_initials, fabricante_name in FABRICANTE_CHOICES:
            Fabricante.objects.get_or_create(initials=fabricante_initials, name=fabricante_name)

        for category_initials, category_name in CATEGORY_CHOICES:
            Category.objects.get_or_create(initials=category_initials, name=category_name)

class Item(models.Model):
    title = models.CharField(max_length=100)
    order_price = models.FloatField(default=0)
    rental_price = models.FloatField(default=0)
    rental_duration_months = models.PositiveIntegerField(default=1)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    disponibility = models.CharField(choices=DISPONIBILITY_CHOICES, max_length=2,null=True)
    selected = models.BooleanField(default = False)
    fabricante = models.ForeignKey(Fabricante, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url_purchase(self):
        return reverse("core:add-to-cart-purchase", kwargs={
            'slug': self.slug
        })
    
    def get_add_to_cart_url_rental(self):
        return reverse("core:add-to-cart-rental", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })
    
    def get_admin_item_panel(self):
        return reverse("core:admin-item", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    user_profile = models.ForeignKey(settings.USER_PROFILE_MODEL,
                             on_delete=models.CASCADE, 
                             blank=True, null=True)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    is_rental = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_default_user_profile(current_user):
        return UserProfile.objects.filter(user=current_user).first()

    def get_total_item_price(self):
        if self.is_rental:
            return self.quantity * self.item.rental_price * self.item.rental_duration_months
        else:
            return self.quantity * self.item.order_price

    def get_final_price(self):
        return self.get_total_item_price()
    
    def get_item_rental_duration(self):
        if self.is_rental:
            return self.item.rental_duration_months
        else:
            return 0  # If not a rental, return 0 duration

    def get_order_item_rental_duration(self):
        return self.get_item_rental_duration()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    user_profile = models.ForeignKey(settings.USER_PROFILE_MODEL,
                             on_delete=models.CASCADE, 
                             blank=True, null=True)                         
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    statement = models.CharField(choices=STATE_CHOICES, max_length=2,null=True, default='En preparacion')
    payment_type = models.BooleanField(default=False)
    shipping = models.BooleanField(default=True, blank=True, null=True)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username
    
    def get_default_user_profile(current_user):
        return UserProfile.objects.filter(user=current_user).first()

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
      
        return total

    def is_shipping_cost(self):
        return self.get_total() >= 50000
    
    def get_final_price(self):
        if self.is_shipping_cost():
            return self.get_total()
        else:
            return self.get_total() + 499.99  


class Address(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_addresses')
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Response(models.Model):
    description = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    opinion = models.ForeignKey('Opinion', related_name='opinion', on_delete=models.CASCADE, blank=True, null=True)                         

class Opinion(models.Model):
    title = models.CharField(max_length = 20)
    description = models.CharField(max_length = 100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <link rel="icon" href="{% static 'img/camionicono.png' %}">

  <title>{% block head_title %}JesseRentals{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    body {
  background-color: #3a3a3a; /* Código de color para negro */
  color: #fff; /* Color del texto, en este caso blanco para contrastar */
}

  table{
    text-decoration-color: white;
  }


    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

<style>
  /* Estilo para la card Caterpillar */
  .caterpillar-card {
    /* Borde de la card */
    border-radius: 10px;
    /* Bordes redondeados */
    overflow: hidden;
    /* Para ocultar cualquier desbordamiento de contenido */
    transition: transform 0.3s;
    /* Efecto de transición en hover */
  }

  .caterpillar-card:hover {
    transform: scale(1.05);
    /* Efecto de escala en hover */
  }

  /* Estilo para el botón de "Añadir al carrito" */
  .caterpillar-card .add-to-cart-btn {
    border-radius: 10px;
    background-color: #ffc107;
    /* Amarillo Caterpillar */
    color: #000;
    /* Texto en negro */
  }

  .caterpillar-card .add-to-cart-btn:hover {
    background-color: #ffca2b;
    /* Amarillo ligeramente más claro en hover */
    color: #000;
  }

  /* Estilo para el precio */
  .caterpillar-card .font-weight-bold {
    color: #000;
    /* Texto del precio en negro */
  }

  /* Add this CSS to your stylesheet or style block */
  .nav-link {
    color: white;
    /* Set the text color to white */
  }

  .nav-item.dropdown:hover .dropdown-menu {
    display: block;
  }

  .nav-item.dropdown:hover .nav-link {
    color: white;
    /* Change text color on hover */
  }

  .nav-item.dropdown .dropdown-menu {
    background-color: black;
    /* Set the background color to black */
  }

  .nav-item.dropdown .dropdown-item {
    color: white;
    /* Set the text color of dropdown items to white */
  }

  .nav-item.dropdown .dropdown-item:hover {
    background-color: #333;
    /* Change background color on hover */
  }
</style>

<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark black lighten-3 mt-3 mb-5">

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'core:home' %}">Todos los resultados</a>
          </li>
          <!-- Category Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Categoría
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% for category in categories %}
              <a class="dropdown-item"
                href="{% url 'core:home-category' category=category.initials %}">{{category.name}}</a>
              {% endfor %}
            </div>
          </li>
          <!-- Fabricante Dropdown -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="fabricanteDropdown" role="button" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Fabricante
            </a>
            <div class="dropdown-menu" aria-labelledby="fabricanteDropdown">
              {% for fabricante in fabricantes %}
              <a class="dropdown-item"
                href="{% url 'core:home-fabricante' fabricante=fabricante.initials %}">{{fabricante.name}}</a>
              {% endfor %}
            </div>
          </li>
          {% if user.is_authenticated and user.is_staff %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:add_item' %}">Añadir Producto</a>
          </li>
          {% endif %}

          <!-- Otros enlaces para las demás categorías -->
        </ul>
        <!-- Links -->

        <form class="form-inline" method="GET">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Buscar producto" aria-label="Buscar producto"
              name="search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card black">

            <div class="view overlay">
              <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="{{ item.get_absolute_url }}" class="white-text">
                <h5>{{ item.category.name }}</h5>
              </a>

              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="white-text">{{ item.title }}
                    <span class="badge badge-pill {{ item.get_label_display }}-color">Nuevo</span>
                    <span class="badge badge-pill badge-warning" style="color: #000 !important;">
                      {{ item.fabricante.name }}
                    </span>
                  </a>
                </strong>
              </h5>

              {% if user.is_authenticated and user.is_staff %}
              <a href="{{ item.get_admin_item_panel }}" class="edit-btn btn btn-info btn-md my-0 p text-light">
                Editar
                <i class="fas fa-edit ml-1"></i>
              </a>
              {% else %}
              {% if item.get_disponibility_display == "Disponible" %}
              <div class="row">
                <div class="col">
                  <a href="{{ item.get_add_to_cart_url_purchase }}" class="btn btn-warning btn-md text-dark">
                    <div class="text-center">
                      Comprar producto <i class="fas fa-shopping-cart ml-1"></i>
                    </div>
                    <h4 class="font-weight-bold">
                      <strong>{{ item.order_price }}€</strong>
                    </h4>
                  </a>
                </div>

                <div class="col">
                  <a href="{{ item.get_add_to_cart_url_rental }}" class="btn btn-warning btn-md text-dark">
                    <div class="text-center">
                      Alquiler mensual <i class="fas fa-shopping-cart ml-1"></i>
                    </div>
                    <h4 class="font-weight-bold">
                      <strong>{{ item.rental_price }}€</strong>
                    </h4>
                  </a>
                </div>
              </div>

              {% else %}
              <a href="">
                <span class="badge red mr-1">{{ item.get_disponibility_display }}</span>
              </a>
              {% endif %}
              {% endif %}



            </div>

          </div>

        </div>
        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->



    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}

  </div>
</main>


{% endblock content %}

templates/order_list.html
{% extends 'base.html' %}

{% block content %}
<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5">
    <h1 class="font-weight-bold text-warning" style="text-shadow: 2px 2px 2px black;">Lista de Pedidos</h1>
    

    {% if orders %}
    <ul class="list-group mt-4">
      {% for order in orders %}
      <li class="list-group-item">
        <span>Ref. Code <strong>{{ order.ref_code }}</strong></span>
        <form method="post" action="{% url 'core:order-list' %}">
          {% csrf_token %}
          <input type="hidden" name="order_id" value="{{ order.id }}">
          <ul class="list-group mt-2 bg-dark">
            <li class="list-group-item list-group-item-dark">Usuario: {{ order.user }}</li>
            <li class="list-group-item list-group-item-dark">Productos: 
              {% for order_item in order.items.all %}
                {{ order_item.quantity }} x 
                <strong>{{ order_item.item }}</strong> ({{ order_item.item.fabricante }}),
              {% endfor %}
            </li>
            <li class="list-group-item list-group-item-dark">Fecha: {{ order.start_date }}</li>
            <li class="list-group-item list-group-item-dark">Dirección: {{ order.shipping_address.street_address }}</li>
            <li class="list-group-item list-group-item-dark">Forma de pago: 
              {% if order.payment_type == 1 %}
              Contrareembolso
              {% else %}
              Tarjeta de Credito</li>
              {% endif %}
            <li class="list-group-item list-group-item-dark"><strong>Estado: {{ order.get_statement_display }}</strong>
              <select id="order_state" name="order_state">
                {% for choice in state %}
                  <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
              </select>
            </li>
            <li class="list-group-item list-group-item-dark">
              <button type="submit">Guardar Estado</button>
            </li>
            
          </ul>
        </form>
      </li>
      {% endfor %}
      
    </ul>
    
    
    {% else %}
    <p class="text-warning">No hay pedidos en curso ni pendientes.</p>
    {% endif %}
  </div>
</main>
{% endblock %}

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
<main>
    <div class="container">

        <div class="table-responsive text-nowrap">
            <h2 class="text-white">Resumen del pedido</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" class="text-white">#</th>
                        <th scope="col" class="text-white">Producto</th>
                        <th scope="col" class="text-white">Precio</th>
                        <th scope="col" class="text-white">Cantidad</th>
                        <th scope="col" class="text-white">Meses</th>
                        <th scope="col" class="text-white">Total Precio Productos</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order_item in object.items.all %}
                    <tr>
                        <th scope="row" class="text-white">{{ forloop.counter }}</th>
                        <td class="text-white">{{ order_item.item.title }}</td>
                        {% if not order_item.is_rental %}
                        <td class="text-white">{{ order_item.item.order_price }}&euro;</td>
                        {% else %}
                        <td class="text-white">{{ order_item.item.rental_price }}&euro;</td>
                        {% endif %}

                        <td class="text-white">
                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i
                                    class="fas fa-minus mr-2 text-white"></i></a>
                            {{ order_item.quantity }}
                            {% if not order_item.is_rental %}
                            <a href="{% url 'core:add-to-cart-purchase' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2 text-white"></i></a>
                            {% else %}
                            <a href="{% url 'core:add-to-cart-rental' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2 text-white"></i></a>
                            {% endif %}
                        </td>

                        {% if order_item.is_rental %}
                        <td class="text-white">
                            <a href="{% url 'core:remove-month-from-cart' order_item.item.slug %}"><i
                                    class="fas fa-minus mr-2 text-white"></i></a>
                            {{ order_item.item.rental_duration_months }}
                            <a href="{% url 'core:add-month-to-cart' order_item.item.slug %}"><i
                                    class="fas fa-plus ml-2 text-white"></i></a>
                        </td>
                        {% else %}
                        <td></td>
                        {% endif %}

                        <td class="text-white">
                            {% if order_item.item.discount_price %}
                            ${{ order_item.get_total_discount_item_price }}
                            <span class="badge badge-primary">Saving {{ order_item.get_amount_saved }}&euro;</span>
                            {% else %}
                            {{ order_item.get_total_item_price }}&euro;
                            {% endif %}
                            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                <i class="fas fa-trash float-right"></i>
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan='6' class="text-white">Tu cesta está vacía</td>
                    </tr>
                    {% endfor %}
                    {% if object.coupon %}
                    <tr>
                        <td colspan="6" class="text-white"><b>Coupon</b></td>
                        <td class="text-white"><b>-{{ object.coupon.amount }}&euro;</b></td>
                    </tr>
                    {% endif %}
                    {% if object.get_total %}
                    <tr>
                        <td colspan="5" class="text-white"><b>Total Pedido</b></td>
                        <td class="text-white"><b>{{ object.get_total }}&euro;</b></td>
                    </tr>
                    <tr>
                        <td colspan="6">
                            <a class='btn btn-warning float-right ml-2 text-white' href='/checkout/'>Proceder al
                                pago</a>
                            <a class='btn btn-primary float-right text-white' href='/'>Continuar comprando</a>
                        </td>
                    </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>

    </div>
</main>

{% endblock content %}